version: "2"

services:
  php:
    container_name: openloyalty_backend
    build:
      context: '../'
      dockerfile: './docker/gcloud/php/fpm-dockerfile'
    links:
      - db
      - elk
      - mail
    depends_on:
      - db
    env_file:
        - .env
    environment:
      - frontend_customer_panel_url=http://ol.pointhacks.com:8183/client
      - frontend_password_reset_url=ol.pointhacks.com:8183/client#!/password/reset
  nginx:
    container_name: openloyalty_frontend
    build:
      context: '../'
      dockerfile: './docker/gcloud/web/app-dockerfile'
    links:
      - php
    ports:
      - "80:80"
      # - "8182:3001" -- Domains used instead
      # - "8183:3002"
      # - "8184:3003"
    command: bash -c "sed -i -e 's@"http://openloyalty.localhost/api"@'\"http://ol.pointhacks.com/api\"'@g' /var/www/openloyalty/front/config.js && nginx -g 'daemon off;'"
    volumes:
      - './gcloud/web:/etc/nginx/conf.d'
  elk:
    container_name: openloyalty_elk
    build:
      context: '../'
      dockerfile: './docker/base/elasticsearch-dockerfile'
  db:
    container_name: openloyalty_db
    image: postgres:9
    env_file:
        - .env
  mail:
    container_name: openloyalty_mail
    image: mailhog/mailhog
    ports:
      - "8186:8025"
